### PR TITLE
Fix GetK8sVersion for all the hosted providers

### LINKED ISSUE #147: Fix defaultEKS function to fetch from ListEKSAvailableVersions
Fetch EKS versions from https://github.com/rancher/shepherd/blob/main/extensions/clusters/kubernetesversions/available.go#L294

### PR DESCRIPTION
**Pull request by valaparthvi**
### What does this PR do?
1. Simplify `GetK8sVersion` for all the hosted providers to call list single variants of each minor version and return a version based on `forUpgrade` parameter.
2. Rename AKS `ListSingleVariantAKSAvailableVersions` to `ListSingleVariantAKSAllVersions`, also modify it to return the versions in descending order 1.28.3, 1.28.0, etc, and modify the tests using this function with required changes.

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #147

### Checklist:
- [ ] Squashed commits into logical changes
- [ ] Documentation
- [x] GitHub Actions (if applicable) - [GKE P0/Support Matrix :green_circle:  (import k8s upgrade is re-run)](https://github.com/rancher/hosted-providers-e2e/actions/runs/10593165181/job/29354275476), [GKE P0 Import re-run :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/10597550011) [EKS P0/Support Matrix :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/10593162397/job/29354269851), [AKS P0/Support Matrix :green_circle: (Failure with 1.27.16 is also reproducible manually and looks like a temporary failure)](https://github.com/rancher/hosted-providers-e2e/actions/runs/10593159634/job/29354269902)
1. GKE P1 on 2.9-head uses 1.30.3-gke.1969000 - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575523066/job/29299429366
2. GKE P0 on 2.8-head uses 1.27.16-gke.1234000 (upgrade=true), and 1.28.13-gke.1006000 (upgrade=false) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575520397/job/29299407442
3. GKE Sync on 2.8-head - https://github.com/rancher/hosted-providers-e2e/actions/runs/10580174818
4. AKS P1 on 2.9-head uses 1.30.3 - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575516457/job/29299399455
5. AKS P0 on 2.8-head uses 1.27.16 (upgrade=true), and 1.28.12 (upgrade=false) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575511076/job/29299401402
6. EKS P0 on 2.8-head uses 1.27 (ugprade=true), and 1.28 (upgrade=false) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575527300/job/29301589326
7. EKS P1 on 2.9-head - https://github.com/rancher/hosted-providers-e2e/actions/runs/10578087657
8. EKS Sync on 2.8-head - https://github.com/rancher/hosted-providers-e2e/actions/runs/10580193647

### CODE REVIEW

File: hosted/eks/helper/helper_cluster.go [hunk 1]
```diff
@@ -572,44 +581,22 @@ func DeleteEKSClusterOnAWS(region string, clusterName string) error {
...
 	if k8sVersion := helpers.DownstreamK8sMinorVersion; k8sVersion != "" {
 		return k8sVersion, nil
 	}
-	return defaultEKS(client, forUpgrade)
+	allVariants, err := ListEKSAllVersions(client)
+	if err != nil {
+		return "", err
+	}
+
+	if forUpgrade {
```
Comment (cpinjani) [inline hosted/eks/helper/helper_cluster.go:595]: These could be a common helper function

**Comment by cpinjani** [comment]
Changes looks fine, for 2.9 please also run P0, SupportMatrix

File: hosted/eks/helper/helper_cluster.go (hunk 1 above)
Comment (valaparthvi) [reply hosted/eks/helper/helper_cluster.go:595]: Do you mean the entire `GetK8sVersion` can be moved to helper_common?

**Comment by valaparthvi** [comment]
> Changes looks fine, for 2.9 please also run P0, SupportMatrix

1. GKE P0/Support Matrix 🟢 (import k8s upgrade is re-run) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10593165181/job/29354275476
2. GKE P0 Import re-run :runner: - https://github.com/rancher/hosted-providers-e2e/actions/runs/10597550011
3. EKS P0/Support Matrix 🟢 - https://github.com/rancher/hosted-providers-e2e/actions/runs/10593162397/job/29354269851
4. AKS P0/Support Matrix 🟢 (Failure with 1.27.16 is also reproducible manually and looks like a temporary failure) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10593159634/job/29354269902

**Comment by cpinjani** [comment]
> > Changes looks fine, for 2.9 please also run P0, SupportMatrix
> 
> 1. GKE P0/Support Matrix 🟢 (import k8s upgrade is re-run) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10593165181/job/29354275476
> 2. GKE P0 Import re-run 🟢  - https://github.com/rancher/hosted-providers-e2e/actions/runs/10597550011
> 3. EKS P0/Support Matrix 🟢 - https://github.com/rancher/hosted-providers-e2e/actions/runs/10593162397/job/29354269851
> 4. AKS P0/Support Matrix 🟢 (Failure with 1.27.16 is also reproducible manually and looks like a temporary failure) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10593159634/job/29354269902

JFYI, `auto-aks-hp-ci-gcqfz is on version 1.27.16 which is not supported in this region`

**Comment by valaparthvi** [comment]
>JFYI, auto-aks-hp-ci-gcqfz is on version 1.27.16 which is not supported in this region

I was able to reproduce it manually on Rancher and Azure console. Even though 1.27.16 is visible on Azure console and rancher, I was not able to create the cluster.
