### PR TITLE
Fix AKS failure

### LINKED ISSUE #192: Refactor AKS Test - CaseID 217
The automated AKS test needs to updated since it fails when run in parallel nodes, `should successfully create 2 clusters in the same RG`
https://github.com/rancher/hosted-providers-e2e/actions/runs/11515508794/job/32074058341#step:17:195

### PR DESCRIPTION
**Pull request by valaparthvi**
### What does this PR do?
- Fix test case ID from 217 to 214 and fix the test.
- Add a new function CreateAKSRGOnAzure to create RG via CLI
- Increase timeout for a failing test

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #192 

### Checklist:
- [ ] Squashed commits into logical changes
- [ ] Documentation
- [ ] GitHub Actions (if applicable) - [P1 Prov](https://github.com/rancher/hosted-providers-e2e/actions/runs/12677170701), [P1 Import](https://github.com/rancher/hosted-providers-e2e/actions/runs/12670126790)

### CODE REVIEW

File: hosted/aks/helper/helper_cluster.go [hunk 1]
```diff
@@ -496,6 +493,20 @@ func CreateAKSClusterOnAzure(location string, clusterName string, k8sVersion str
...
 
+// CreateAKSRGOnAzure creates resource group on azure via CLI
+func CreateAKSRGOnAzure(name, location string) error {
+	fmt.Println("Creating AKS resource group ...")
+	rgargs := []string{"group", "create", "--location", location, "--resource-group", name, "--subscription", subscriptionID}
+	fmt.Printf("Running command: az %v\n", rgargs)
+
+	out, err := proc.RunW("az", rgargs...)
+	if err != nil {
+		return errors.Wrap(err, "Failed to create cluster: "+out)
```
Comment (cpinjani) [inline hosted/aks/helper/helper_cluster.go:504]:
```suggestion
		return errors.Wrap(err, "Failed to create resource group: "+out)
```

File: hosted/aks/p1/p1_provisioning_test.go [hunk 2]
```diff
@@ -25,14 +25,18 @@ import (
...
+		GinkgoLogr.Info(fmt.Sprintf("Running on process: %d", GinkgoParallelProcess()))
 		var err error
 		k8sVersion, err = helper.GetK8sVersion(ctx.RancherAdminClient, ctx.CloudCredID, location, false)
 		Expect(err).NotTo(HaveOccurred())
 		GinkgoLogr.Info(fmt.Sprintf("Using K8s version %s for cluster %s", k8sVersion, clusterName))
 	})
+
 	AfterEach(func() {
 		if ctx.ClusterCleanup && (cluster != nil && cluster.ID != "") {
+			GinkgoLogr.Info(fmt.Sprintf("Cleaning up resources %s %s", cluster.Name, cluster.ID))
```
Comment (cpinjani) [inline hosted/aks/p1/p1_provisioning_test.go:39]:
```suggestion
			GinkgoLogr.Info(fmt.Sprintf("Cleaning up resources, cluster: %s %s", cluster.Name, cluster.ID))
```

**Review by cpinjani — APPROVED** [review]
looks good based on the CI runs, thanks
