### PR TITLE
Fix EKS cleanup on a new nodegroup addition for imported clusters

### LINKED ISSUE #153: Fix EKS cleanup when a new nodepool is added
eksctl is not able to deleted if the cluster is modified when a new nodepool is added. Because of this, janitor cleanup does not work as expected and the cluster needs to be manually deleted.

### PR DESCRIPTION
**Pull request by valaparthvi**
### What does this PR do?
1. Modify `DeleteEKSClusterOnAWS` to list all the nodegroups and delete them before deleting the cluster.
2. Rename `eks_region` to `region` to conform with the Go naming convention that says 'Names in Go should in general not contain underscores'.
3. Fix EKS cluster not cleaned up for "reimport an existing cluster".
    <details><summary>Details</summary>

      ```
      • [842.949 seconds]
      P1Import when a cluster is imported Reimporting/Editing a cluster with invalid config Reimport a cluster to Rancher should fail
      /home/gh-runner/actions-runner/_work/hosted-providers-e2e/hosted-providers-e2e/hosted/eks/p1/p1_import_test.go:146
      
        Captured StdOut/StdErr Output >>
        Creating EKS cluster ...
        Running command: eksctl [create cluster --region=*** --name=auto-eks-hp-ci-qvvaw --version=1.30 --nodegroup-name ranchernodes --nodes 1 --managed --tags aws-janitor/marked-for-deletion=true,owner=hosted-providers-qa-ci-gh-runner,testfilenumber=line146_p1_import_test]
        Created EKS cluster:  auto-eks-hp-ci-qvvaw
        time="2024-08-26T16:03:02Z" level=info msg="Cluster status is active!"
        Skipping downstream cluster deletion:  auto-eks-hp-ci-qvvaw
        << Captured StdOut/StdErr Output
      
        Timeline >>
        "level"=0 "msg"="Using kubernetes version 1.30 for cluster auto-eks-hp-ci-qvvaw"
        Qase ID 101 created for run ID 860 on project HP
        << Timeline
      ------------------------------
      S
      ```

</details> 

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #153

### Checklist:
- [ ] Squashed commits into logical changes
- [ ] Documentation
- [X] GitHub Actions (if applicable) - [p0 import] ~https://github.com/rancher/hosted-providers-e2e/actions/runs/10558562916/job/29248333175,~ [ :green_circle: ] https://github.com/rancher/hosted-providers-e2e/actions/runs/10562272067

### CODE REVIEW

File: hosted/eks/helper/helper_cluster.go [hunk 1]
```diff
@@ -540,9 +540,27 @@ func DeleteEKSClusterOnAWS(eks_region string, clusterName string) error {
...
 
+	fmt.Println("Deleting all the nodegroups ...")
+	ngNames, err := GetFromEKS(region, clusterName, "nodegroup", ".[].Name")
+	if err != nil {
+		return errors.Wrap(err, "Failed to list nodegroup for deletion")
+	}
+
+	if ngNames != "" {
+		for _, ngName := range strings.Split(ngNames, "\n") {
+			args := []string{"delete", "nodegroup", "--region", region, "--name", ngName, "--cluster", clusterName, "--disable-eviction", "--wait"}
```
Comment (cpinjani) [inline hosted/eks/helper/helper_cluster.go:551]: nit:
Could we use _ModifyEKSNodegroupOnAWS_ here ?

Comment (valaparthvi) [reply hosted/eks/helper/helper_cluster.go:551]: Oh yes, of course. I was going to use that, and then forgot :sweat_smile:

**Review by cpinjani — APPROVED** [review]
lgtm.. based on latest run.
