### PR TITLE
Fix for chart support tests

### LINKED ISSUE #117: v2.9 - Analyze and fix failing jobs
- GKE support_matrix_provisioning: https://github.com/rancher/hosted-providers-e2e/actions/runs/9478298953, k8s_chart_support: https://github.com/rancher/hosted-providers-e2e/actions/runs/9486026270
- EKS k8s_chart_support: https://github.com/rancher/hosted-providers-e2e/actions/runs/9486027541/job/26165705901,
p0_importing: https://github.com/rancher/hosted-providers-e2e/actions/runs/9477951949 (failing on v2.8 also)

### PR DESCRIPTION
**Pull request by cpinjani**
### What does this PR do?
Adds a check to ensure Rancher API is available after chart is re-installed to latest version

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #117 

### Checklist:
- [x] GitHub Actions
[AKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/9567909734), [EKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/9576500166), [GKE](https://github.com/rancher/hosted-providers-e2e/actions/runs/9565279217)

### CODE REVIEW

File: hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go [hunk 1]
```diff
@@ -104,21 +118,26 @@ func commonchecks(client *rancher.Client, cluster *management.Cluster) {
...
 
+		By("ensuring that rancher is up", func() {
+			helpers.CheckRancherPods(false)
+		})
+
 		// We do not use WaitClusterToBeUpgraded because it has been flaky here and times out
-		var upgradeSuccessful bool
 		Eventually(func() bool {
-			for i := range cluster.EKSConfig.NodeGroups {
+			ginkgo.GinkgoLogr.Info("Waiting for the node count change to appear in EKSStatus.UpstreamSpec ...")
```
Comment (thehejik) [inline hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go:134]:
```suggestion
			GinkgoLogr.Info("Waiting for the node count change to appear in EKSStatus.UpstreamSpec ...")
```

File: hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go [hunk 2]
```diff
@@ -5,6 +5,7 @@ import (
 	"testing"
 	"time"
 
+	"github.com/onsi/ginkgo/v2"
```
Comment (thehejik) [inline hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go:8]:
```suggestion

```

Comment (thehejik) [reply hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go:8]: This shouldn't be needed once you replace `ginko.GinkgoLogr.Info` by `GinkgoLogr.Info` later.

**Review by thehejik — APPROVED** [review]
LGTM
